package com.aneeque.backendservice.enums;

import lombok.Data;

/**
 * @author Okala III
 */

public enum UserPrivilege {

    VIEW_USERS("","USER_MANAGEMENT"),
    FILTER_USERS_BY_ROLE("","USER_MANAGEMENT"),
    CREATE_USERS("","USER_MANAGEMENT"),
    DEACTIVATE_USERS("","USER_MANAGEMENT"),
    DELETE_USERS("","USER_MANAGEMENT"),
    UNLOCK_USER("","USER_MANAGEMENT"),
    USER_LOGIN("","USER_MANAGEMENT"),
    CREATE_ROLE("","USER_MANAGEMENT"),
    ASSIGN_PERMISSION_TO_ROLE("","USER_MANAGEMENT"),
    ASSIGN_ROLE_TO_USER("","USER_MANAGEMENT"),
    ASSIGN_PERMISSION_TO_USER("","USER_MANAGEMENT"),
    VIEW_PERMISSIONS("","USER_MANAGEMENT"),
    VIEW_ROLES("","USER_MANAGEMENT"),
    VIEW_PERMISSIONS_ASSIGNED_TO_ROLE("","USER_MANAGEMENT"),
    VIEW_PERMISSIONS_ASSIGNED_TO_USER("","USER_MANAGEMENT"),


    CREATE_ORDERS("","ADMIN_ORDER_MANAGEMENT"),
    EXPORT_ORDERS_EXCEL("","ADMIN_ORDER_MANAGEMENT"),
    EMAIL_CUSTOMER("","ADMIN_ORDER_MANAGEMENT"),
    GENERATE_INVOICE("","ADMIN_ORDER_MANAGEMENT"),
    UPDATE_ORDER_STATUS("","ADMIN_ORDER_MANAGEMENT"),
    GENERATE_BARCODE("","ADMIN_ORDER_MANAGEMENT"),
    NOTIFY_FULFILLMENT_TEAM("","ADMIN_ORDER_MANAGEMENT"),
    GENERATE_REPORTS_OR_ANALYTICS("","ADMIN_ORDER_MANAGEMENT"),
    CHANGE_ORDER_SETTINGS("","ADMIN_ORDER_MANAGEMENT"),

    TRACK_INVENTORY_LEVEL("","ADMIN_INVENTORY_MANAGEMENT"),
    THRESHOLD_NOTIFICATION_REORDER_POINT("","ADMIN_INVENTORY_MANAGEMENT"),
    ADD_PRODUCT("","ADMIN_INVENTORY_MANAGEMENT"),
    EDIT_PRODUCT("","ADMIN_INVENTORY_MANAGEMENT"),
    DELETE_PRODUCT("","ADMIN_INVENTORY_MANAGEMENT"),
    GENERATE_MASTER_LIST("","ADMIN_INVENTORY_MANAGEMENT"),
    IMPORT_PRODUCT_EXCEL("","ADMIN_INVENTORY_MANAGEMENT"),
    EXPORT_PRODUCT_EXCEL("","ADMIN_INVENTORY_MANAGEMENT"),
    CREATE_CATEGORY("","ADMIN_INVENTORY_MANAGEMENT"),
    CREATE_TAG("","ADMIN_INVENTORY_MANAGEMENT"),
    GENERATE_PURCHASE_ORDER("","ADMIN_INVENTORY_MANAGEMENT"),
    BULK_EDITING("","ADMIN_INVENTORY_MANAGEMENT"),
    BULK_DELETE("","ADMIN_INVENTORY_MANAGEMENT"),
    ;

    public String module;
    public String description;

    UserPrivilege(String description, String module) {
        this.module = module;
        this.description = description;
    }

    UserPrivilege(String module) {
        this.module = module;
    }
}
