version: '3.1'
services:
  app:
    container_name: aneeque_backend
    image: aneeque_backend
    build: ./
#    ports:
#      - "8089:8089"
    network_mode: host
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password12
      - MYSQL_DATABASE=aneeque_dev
    volumes:
      - ./database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
    ports:
      - 8787:80
    volumes:
      - /sessions
    links:
      - db