server:
  port: ${SERVER_PORT:8789}
  error:
    include-message: always
    include-binding-errors: always


spring:
  flyway:
    url : 'jdbc:mysql://0.0.0.0:3306/aneeque_dev?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false'
    password: ${DATABASE_PASSWORD:root}
    user: ${DATABASE_USERNAME:root}
    enabled: false
    out-of-order: true
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: 'classpath:db/migration'
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 15MB

  datasource:
    password: ${DATABASE_PASSWORD:root}
    url: jdbc:mysql://0.0.0.0:3306/aneeque_dev?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATABASE_USERNAME:root}

  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true

        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  profiles:
    active: local


payment-platform:
  seerbit:
    check-transaction-status-url: "https://seerbitapi.com/api/v2/payments/query/"
    get-token-url: "https://seerbitapi.com/api/v2/encrypt/keys"
    public-key: "SBTESTPUBK_qv5b1rVlVVmxFPiPmr5IHtQIvvYAZ1Yg"
    private-key: "SBTESTSECK_HQuL3EJpMfOdAPQaASwdC3Y2aZxDD8fUhvHKLrKo"

user-mgnt:
  account:
    activation-email:
      template: "Your account activation Token %s . The token expires at %s"
    activation-token:
      lifetime:
        minutes: 10

  jwt:
    secret-key: ${JWT_SECRET_KEY:secret }
    lifetime:
      hours:  6
      minutes: 5
      seconds: 0
      milli-seconds: 0
  trusted-origins: "*"

com.aneeque:
  paystack:
    secretKey: ${PAYSTACK_SECRET_KEY:sk_test_7089c6135b18d0f15265f111179c7e73dd4f7092 }
    publicKey: ${PAYSTACK_PUBLIC_KEY:pk_test_05aaa4b1a416f628956233cbec2a8b00de338f0f }
  file:
    upload:
      format: pdf,jpg,png,zip,rar
    directory: "/opt/aneeque/uploads/"

